name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.CI_CD_BOSTON_TOKEN}}
          heroku_app_name: "git-heroku-deploy" #Must be unique in Heroku
          heroku_email: "h.hurchand@gmail.com"
